### ISSUE TITLE
Unable to download Project 64

### ISSUE THREAD

**Issue by Stellarvideo588** [Rosalie241/BetterMajorasMaskInstaller#17] opened 2021-08-14 19:58 UTC
When I attempted to start the download it gave me this error 

Downloading Project64...
Downloading Project64 Failed
Cannot find artifact containing "Win32" in the filename
   at BetterMajorasMaskInstaller.ComponentDownloader.AppVeyorUrlInfo(UrlInfo urlInfo)
   at BetterMajorasMaskInstaller.ComponentDownloader.DownloadComponent(InstallerComponent& component, String directory)

**Comment by Rosalie241** [comment] 2021-08-14 20:04
Are you using the latest version of the installer? Try re-downloading the latest version if you're unsure.

**Comment by Rosalie241** [comment] 2021-09-15 21:32
can't reproduce & no reply since August, closing.

**Closed by Rosalie241** 2021-09-15 21:32 UTC
